FROM node:22-alpine

WORKDIR /Payments

COPY package*.json ./

RUN npm install

# Install ts-node globally
RUN npm install -g ts-node
RUN npm install typescript --save-dev
COPY . .

# Build the project during image creation
RUN npm run build

ENV PORT=3000
EXPOSE 3000

# Start the app when container runs
CMD [ "npm", "start" ]
